core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm
from django.contrib.auth.views import LogoutView

app_name = "core"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("add_retailer/", views.add_retailer, name="add_retailer"),
    path("", auth_views.LoginView.as_view(
        template_name='core/login.html',
        authentication_form=LoginForm), name="login"),
    path('logout/', LogoutView.as_view(next_page=''), name='logout'),
]

e_commerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path("", include("core.urls")),
    path("items/", include("items.urls")),
    path("admin/", admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('view_cart/', views.show_cart_items, name='view_cart'),
    path('confirm_order/', views.confirm_order, name='confirm_order'),
    path('place_order/', views.place_order, name='place_order'),
]

items/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Item(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    Created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name',]
    
    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    product_count = models.PositiveIntegerField(default=0)
    total_price = models.FloatField(default=0.0)

    def update_totals(self):
        # Calculate total price and product count from related CartItems
        cart_items = self.cartitem_set.all()
        total_price = sum(cart_item.quantity * cart_item.item.price for cart_item in cart_items)
        product_count = sum(cart_item.quantity for cart_item in cart_items)

        # Update the fields in the Cart model
        self.total_price = total_price
        self.product_count = product_count
        self.save()

    def __str__(self):
        return f"Cart of {self.user.username}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    amount = models.FloatField(default=0.0)

    def __str__(self):
        return f"{self.quantity} x {self.item.name} in cart of {self.cart.user.username}"
    

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    total_price = models.FloatField()  
    
    def __str__(self):
        return f"Order {self.id} by {self.user.username}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    amount = models.FloatField()

    def __str__(self):
        return f"{self.quantity} x {self.item.name} in order {self.order.id}"

items/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'mt-2 w-full py-4 px-6 rounded-xl border border-gray-400'
class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'price', 'image']
    
        widgets = {
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES,}),
            'description': forms.Textarea(attrs={'class': INPUT_CLASSES,}),
            'price': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'image': forms.FileInput(attrs={'class': INPUT_CLASSES}),
        }

items/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
from django.middleware.csrf import get_token
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import json

from .forms import NewItemForm
from .models import Item, Cart, CartItem, Order, OrderItem

# Create your views here.
@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        
        if form.is_valid():
            form.save()
            return redirect('core:index')

    form = NewItemForm()

    return render(request, 'items/form.html', {
        'form': form,
        'title': 'New Item',
    })

@login_required
@require_POST
def add_to_cart(request):
    try:
        data = json.loads(request.body)
        item_id = data.get('item_id')
        quantity = data.get('quantity')

        item = get_object_or_404(Item, id=item_id)
        cart, created = Cart.objects.get_or_create(user=request.user)
        cart_item, created = CartItem.objects.get_or_create(cart=cart, item=item)
        cart_item.quantity += int(quantity)
        cart_item.amount = int(item.price) * int(quantity)
        cart_item.save()
        cart.update_totals()
        
        return JsonResponse({'success': True})
    except Exception as e:
        return JsonResponse({'success': False, 'error': str(e)}, status=500)
    
@login_required
def show_cart_items(request):
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart.update_totals()
    cart_items = CartItem.objects.filter(cart__user=request.user)
        
    return render(request, 'items/view_cart.html', {
        'cart_items': cart_items,
        'cart': cart,
    })

@login_required
def confirm_order(request):
    user = request.user
    try:
        cart = Cart.objects.get(user=user)
    except Cart.DoesNotExist:
        return JsonResponse({'success': False, 'error': 'Cart not found'})
    
    cart_items = CartItem.objects.filter(cart=cart)
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart.update_totals()

    if not cart_items.exists():
        return JsonResponse({'success': False, 'error': 'No items in cart'})

    return render(request, 'items/confirm_order.html', {
        'cart_items': cart_items,
        'cart': cart,})

@login_required
def place_order(request):
    user = request.user
    try:
        cart = Cart.objects.get(user=user)
    except Cart.DoesNotExist:
        return JsonResponse({'success': False, 'error': 'Cart not found'})
    
    cart_items = CartItem.objects.filter(cart=cart)

    if not cart_items.exists():
        return JsonResponse({'success': False, 'error': 'No items in cart'})

    order = Order.objects.create(
        user=user,
        total_price=cart.total_price
    )

    for cart_item in cart_items:
        OrderItem.objects.create(
            order=order,
            item=cart_item.item,
            quantity=cart_item.quantity,
            amount=cart_item.item.price * cart_item.quantity
        )

    cart_items.delete()  # Clear the cart items after creating the order
    cart.delete() # Reset the cart totals

    return JsonResponse({'success': True})

items/templates/items/confirm_order.html
{% extends 'core/base.html' %}

{% block title %}Cart Items{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Cart Items</h2>
        
        {% if cart_items %}
            <table class="table-auto w-full bg-white rounded-lg shadow-lg">
                <thead>
                    <tr>
                        <th class="px-4 py-2">Name</th>
                        <th class="px-4 py-2">Quantity</th>
                        <th class="px-4 py-2">Price</th>
                        <th class="px-4 py-2">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                        <tr>
                            <td class="border px-4 py-2">{{ cart_item.item.name }}</td>
                            <td class="border px-4 py-2">{{ cart_item.quantity }}</td>
                            <td class="border px-4 py-2">₹{{ cart_item.item.price }}</td>
                            <td class="border px-4 py-2">₹{{ cart_item.amount }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="text-center mt-6">
                <p class="mt-6 mb-4 text-2xl font-semi-bold text-center">Total Price: ₹{{ cart.total_price }}</p>
                <button id="confirmOrderButton" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Confirm Order</button>
            </div>
        {% else %}
            <p class="mb-12 text-2xl text-center font-bold">No items in the cart.</p>
            <div class="text-center mt-6">
                <a href="{% url 'core:index' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Home</a>
            </div>
        {% endif %}
    </div>

    <!-- Notification Template -->
    <div id="successNotification" class="hidden p-4 text-green-900 bg-green-100 border border-green-200 rounded-md">
        <div class="flex justify-between flex-wrap">
            <div class="w-0 flex-1 flex">
                <div class="mr-3 pt-1">
                    <svg width="26" height="26" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                        <path d="M8.445 12.6675A.9.9 0 0 0 7.1424 13.91l2.5726 2.7448c.3679.3856.9884.3689 1.335-.036l5.591-7.0366a.9.9 0 0 0-1.3674-1.1705l-4.6548 5.9132a.4.4 0 0 1-.607.0252l-1.567-1.6826zM1.9995 12c0-5.5 4.5-10 10-10s10 4.5 10 10-4.5 10-10 10-10-4.5-10-10z"></path>
                    </svg>
                </div>
                <div>
                    <h4 class="text-md leading-6 font-medium">
                        Order confirmed successfully!
                    </h4>
                    <p class="text-sm">
                        Your order has been placed successfully.
                    </p>
                    <div class="flex mt-3">
                        <a href="{% url 'core:index' %}" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-green-700 text-base font-medium text-white hover:bg-green-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 sm:w-auto sm:text-sm">
                            Go to Home
                        </a>
                    </div>
                </div>
            </div>
            <div>
                <button type="button" class="rounded-md focus:outline-none focus:ring-2 focus:ring-green-500" onclick="document.getElementById('successNotification').classList.add('hidden');">
                    <svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                        <path d="M17.6555 6.3331a.9.9 0 0 1 .001 1.2728l-4.1032 4.1085a.4.4 0 0 0 0 .5653l4.1031 4.1088a.9002.9002 0 0 1 .0797 1.1807l-.0806.092a.9.9 0 0 1-1.2728-.0009l-4.1006-4.1068a.4.4 0 0 0-.5662 0l-4.099 4.1068a.9.9 0 1 1-1.2738-1.2718l4.1027-4.1089a.4.4 0 0 0 0-.5652L6.343 7.6059a.9002.9002 0 0 1-.0796-1.1807l.0806-.092a.9.9 0 0 1 1.2728.0009l4.099 4.1055a.4.4 0 0 0 .5662 0l4.1006-4.1055a.9.9 0 0 1 1.2728-.001z"></path>
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const confirmOrderButton = document.getElementById('confirmOrderButton');
            const successNotification = document.getElementById('successNotification');

            confirmOrderButton.addEventListener('click', function (event) {
                fetch('{% url "items:place_order" %}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        successNotification.classList.remove('hidden');
                    } else {
                        alert('Failed to confirm order: ' + data.error);
                    }
                })
                .catch(error => console.error('Error:', error));
            });
        });
    </script>
{% endblock %}

items/templates/items/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors in form.non_field_errord %}
    <div class=" mb-3 p-6 bg-red-100 rounded relative" role="alert">
        {% for field in form %}
            {{ field.errors }}
        {% endfor %}

        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-red-500 hover:bg-red-700 rounded-xl text-white">Add Item</button>

</form>


{% endblock %}

items/templates/items/order.html
{% extends 'core/base.html' %}

{% block title %}Cart Items{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Cart Items</h2>
        
        {% if cart_items %}
            <table class="table-auto w-full bg-white rounded-lg shadow-lg">
                <thead>
                    <tr>
                        <th class="px-4 py-2">Name</th>
                        <th class="px-4 py-2">Quantity</th>
                        <th class="px-4 py-2">Price</th>
                        <th class="px-4 py-2">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                        <tr>
                            <td class="border px-4 py-2">{{ cart_item.item.name }}</td>
                            <td class="border px-4 py-2">{{ cart_item.quantity }}</td>
                            <td class="border px-4 py-2">₹{{ cart_item.item.price }}</td>
                            <td class="border px-4 py-2">₹{{ cart_item.amount }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="text-center mt-6">
                <p class="mt-6 mb-4 text-2xl font-semi-bold text-center">Total Price: ₹{{ cart.total_price }}</p>
                <button id="confirmOrderButton" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Confirm Order</button>
            </div>
        {% else %}
            <p class="mb-12 text-2xl text-center font-bold">No items in the cart.</p>
            <div class="text-center mt-6">
                <a href="{% url 'core:index' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Home</a>
            </div>
        {% endif %}
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const confirmOrderButton = document.getElementById('confirmOrderButton');

            confirmOrderButton.addEventListener('click', function (event) {
                fetch('{% url "items:confirm_order" %}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        alert('Order confirmed successfully!');
                        // Optionally redirect to another page or update the UI
                    } else {
                        alert('Failed to confirm order: ' + data.error);
                    }
                })
                .catch(error => console.error('Error:', error));
            });
        });
    </script>
{% endblock %}

items/templates/items/view_cart.html
{% extends 'core/base.html' %}

{% block title %}Cart Items{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Cart Items</h2>
        
        {% if cart_items %}
            <div class="grid grid-cols-3 gap-3">
                {% for cart_item in cart_items %}
                    <div class="bg-white p-6 rounded-lg shadow-lg">
                        <img src="{{ cart_item.item.image.url }}" class="rounded-t-xl">
                        <h3 class="text-xl font-semibold">{{ cart_item.item.name }}</h3>
                        <p class="text-gray-500">Quantity: {{ cart_item.quantity }}</p>
                        <p class="text-gray-500">Price: ₹{{ cart_item.item.price }}</p>
                        <p class="text-gray-500">Amount: ₹{{ cart_item.amount }}</p>
                    </div>
                {% endfor %}
            </div>
            <div class="text-center mt-6">
                <p class="mt-6 mb-4 text-2xl font-semi-bold text-center">Total Price: ₹{{ cart.total_price }}</p>
                <a href="{% url 'items:confirm_order' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Confirm Order</a>
            </div>
        {% else %}
            <p class="mb-12 text-2xl text-center font-bold">No items in the cart.</p>
            <div class="text-center mt-6">
                <a href="{% url 'core:index' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Home</a>
            </div>
        {% endif %}
    </div>
{% endblock %}